apiVersion: v1
kind: Pod
metadata:
  name: safe-pod
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
          hostPort: 8081
        - containerPort: 8080
          hostPort: 8087