apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
spec:
  containers:
  - name: web-container
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: log-container
    image: busybox
    command: ["sh", "-c", "while true; do echo 'Logging...'; sleep 10; done"]
    ports:
    - containerPort: 8080