apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: app-container
      image: busybox
      command: ["sh", "-c", "echo Hello from app-container && sleep 3600"]
    - name: sidecar-container
      image: busybox
      command: ["sh", "-c", "echo Hello from sidecar-container && sleep 3600"]